# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detest_ui', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='build',
            old_name='author_id',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='build',
            old_name='testplan_id',
            new_name='testplan',
        ),
        migrations.RenameField(
            model_name='project_platform',
            old_name='platform_id',
            new_name='platform',
        ),
        migrations.RenameField(
            model_name='project_platform',
            old_name='project_id',
            new_name='project',
        ),
        migrations.RenameField(
            model_name='tcattachment',
            old_name='testcase_id',
            new_name='testcase',
        ),
        migrations.RenameField(
            model_name='tcattachment',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='tcexecution',
            old_name='build_id',
            new_name='build',
        ),
        migrations.RenameField(
            model_name='tcexecution',
            old_name='platform_id',
            new_name='platform',
        ),
        migrations.RenameField(
            model_name='tcexecution',
            old_name='status_id',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='tcexecution',
            old_name='testcase_id',
            new_name='testcase',
        ),
        migrations.RenameField(
            model_name='tcexecution',
            old_name='tester_id',
            new_name='tester',
        ),
        migrations.RenameField(
            model_name='tcexecution',
            old_name='testplan_id',
            new_name='testplan',
        ),
        migrations.RenameField(
            model_name='testcase',
            old_name='author_id',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='testcase',
            old_name='previous_version_id',
            new_name='previous_version',
        ),
        migrations.RenameField(
            model_name='testcase',
            old_name='tcexecution_type_id',
            new_name='tcexecution_type',
        ),
        migrations.RenameField(
            model_name='testcase',
            old_name='tcpriority_id',
            new_name='tcpriority',
        ),
        migrations.RenameField(
            model_name='testcase',
            old_name='tcstatus_id',
            new_name='tcstatus',
        ),
        migrations.RenameField(
            model_name='testcase',
            old_name='testsuite_id',
            new_name='testsuite',
        ),
        migrations.RenameField(
            model_name='testplan',
            old_name='author_id',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='testplan',
            old_name='project_id',
            new_name='project',
        ),
        migrations.RenameField(
            model_name='testplan_platforms',
            old_name='platform_id',
            new_name='platform',
        ),
        migrations.RenameField(
            model_name='testplan_platforms',
            old_name='testplan_id',
            new_name='testplan',
        ),
        migrations.RenameField(
            model_name='testplan_testcases',
            old_name='assigned_id',
            new_name='assigned',
        ),
        migrations.RenameField(
            model_name='testplan_testcases',
            old_name='author_id',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='testplan_testcases',
            old_name='platform_id',
            new_name='platform',
        ),
        migrations.RenameField(
            model_name='testplan_testcases',
            old_name='testcase_id',
            new_name='testcase',
        ),
        migrations.RenameField(
            model_name='testplan_testcases',
            old_name='testplan_id',
            new_name='testplan',
        ),
        migrations.RenameField(
            model_name='testsuite',
            old_name='project_id',
            new_name='project',
        ),
        migrations.RenameField(
            model_name='testsuite_ct',
            old_name='child_id',
            new_name='child',
        ),
        migrations.RenameField(
            model_name='testsuite_ct',
            old_name='parent_id',
            new_name='parent',
        ),
        migrations.RemoveField(
            model_name='testcase',
            name='modified_id',
        ),
    ]
